export const FETCH_NOTES_REQUEST = "FETCH_NOTES_REQUEST";
export const FETCH_NOTES_SUCCESSFUL = "FETCH_NOTES_SUCCESSFUL";
export const FETCH_NOTES_FAILED = "FETCH_NOTES_FAILED";
export const FETCH_NOTES_END = "FETCH_NOTES_END";

export const FETCH_NOTE_REQUEST = "FETCH_NOTE_REQUEST";
export const FETCH_NOTE_SUCCESSFUL = "FETCH_NOTE_SUCCESSFUL";
export const FETCH_NOTE_FAILED = "FETCH_NOTE_FAILED";
export const FETCH_NOTE_END = "FETCH_NOTE_END";

export const CREATE_NOTE_READY = "CREATE_NOTE_READY";
export const CREATE_NOTE_REQUEST = "CREATE_NOTE_REQUEST";
export const CREATE_NOTE_SUCCESSFUL = "CREATE_NOTE_SUCCESSFUL";
export const CREATE_NOTE_FAILED = "CREATE_NOTE_FAILED";
export const CREATE_NOTE_END = "CREATE_NOTE_END";

export const UPDATE_NOTE_REQUEST = "UPDATE_NOTE_REQUEST";
export const UPDATE_NOTE_SUCCESSFUL = "UPDATE_NOTE_SUCCESSFUL";
export const UPDATE_NOTE_FAILED = "UPDATE_NOTE_FAILED";
export const UPDATE_NOTE_END = "UPDATE_NOTE_END";

export const DELETE_NOTE_REQUEST = "DELETE_NOTE_REQUEST";
export const DELETE_NOTE_SUCCESSFUL = "DELETE_NOTE_SUCCESSFUL";
export const DELETE_NOTE_FAILED = "DELETE_NOTE_FAILED";
export const DELETE_NOTE_END = "DELETE_NOTE_END";