export const FETCH_NOTE_BOXES_REQUEST = "FETCH_NOTE_BOXES_REQUEST";
export const FETCH_NOTE_BOXES_SUCCESSFUL = "FETCH_NOTE_BOXES_SUCCESSFUL";
export const FETCH_NOTE_BOXES_FAILED = "FETCH_NOTE_BOXES_FAILED";
export const FETCH_NOTE_BOXES_END = "FETCH_NOTE_BOXES_END";

export const FETCH_NOTE_BOX_REQUEST = "FETCH_NOTE_BOX_REQUEST";
export const FETCH_NOTE_BOX_SUCCESSFUL = "FETCH_NOTE_BOX_SUCCESSFUL";
export const FETCH_NOTE_BOX_FAILED = "FETCH_NOTE_BOX_FAILED";
export const FETCH_NOTE_BOX_END = "FETCH_NOTE_BOX_END";

export const CREATE_NOTE_BOX_READY = "CREATE_NOTE_BOX_READY";
export const CREATE_NOTE_BOX_REQUEST = "CREATE_NOTE_BOX_REQUEST";
export const CREATE_NOTE_BOX_SUCCESSFUL = "CREATE_NOTE_BOX_SUCCESSFUL";
export const CREATE_NOTE_BOX_FAILED = "CREATE_NOTE_BOX_FAILED";
export const CREATE_NOTE_BOX_END = "CREATE_NOTE_BOX_END";

export const UPDATE_NOTE_BOX_REQUEST = "UPDATE_NOTE_BOX_REQUEST";
export const UPDATE_NOTE_BOX_SUCCESSFUL = "UPDATE_NOTE_BOX_SUCCESSFUL";
export const UPDATE_NOTE_BOX_FAILED = "UPDATE_NOTE_BOX_FAILED";
export const UPDATE_NOTE_BOX_END = "UPDATE_NOTE_BOX_END";

export const DELETE_NOTE_BOX_REQUEST = "DELETE_NOTE_BOX_REQUEST";
export const DELETE_NOTE_BOX_SUCCESSFUL = "DELETE_NOTE_BOX_SUCCESSFUL";
export const DELETE_NOTE_BOX_FAILED = "DELETE_NOTE_BOX_FAILED";
export const DELETE_NOTE_BOX_END = "DELETE_NOTE_BOX_END";