export const FETCH_TAGS_REQUEST = "FETCH_TAGS_REQUEST";
export const FETCH_TAGS_SUCCESSFUL = "FETCH_TAGS_SUCCESSFUL";
export const FETCH_TAGS_FAILED = "FETCH_TAGS_FAILED";
export const FETCH_TAGS_END = "FETCH_TAGS_END";